# Generated by Django 5.0.4 on 2024-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0002_alter_customuser_age_alter_customuser_favorite_club_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
