# Generated by Django 5.0.4 on 2024-04-05 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("soccerCommunity", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="community",
            old_name="pub",
            new_name="pub_date",
        ),
    ]
